wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.9
    cli_version: 0.17.8
    framework: huggingface
    huggingface_version: 4.38.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1727438812
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      3:
      - 13
      - 23
      4: 3.11.9
      5: 0.17.8
      6: 4.38.2
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
